name: "schema-generator"
version: "0.1.0"
usage: "generate json schema for values yaml"
description: "generate json schema (standard version: https://json-schema.org/draft/2019-09/schema) for values yaml"
ignoreFlags: false
command: "$HELM_PLUGIN_DIR/bin/schema-generator"
hooks:
  install: "cd $HELM_PLUGIN_DIR; scripts/install.sh"
  update: "cd $HELM_PLUGIN_DIR; scripts/install.sh"