// Code generated by "go-enum -type=PatchOperation -transform=lower"; DO NOT EDIT.

package enums

import (
	"database/sql"
	"database/sql/driver"
	"encoding"
	"encoding/json"
	"fmt"
	"strconv"
)

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Replace-0]
	_ = x[Remove-1]
	_ = x[Add-2]
}

const _PatchOperation_name = "replaceremoveadd"

var _PatchOperation_index = [...]uint8{0, 7, 13, 16}

func _() {
	var _nil_PatchOperation_value = func() (val PatchOperation) { return }()

	// An "cannot convert PatchOperation literal (type PatchOperation) to type fmt.Stringer" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ fmt.Stringer = _nil_PatchOperation_value
}

func (i PatchOperation) String() string {
	if i < 0 || i >= PatchOperation(len(_PatchOperation_index)-1) {
		return "PatchOperation(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PatchOperation_name[_PatchOperation_index[i]:_PatchOperation_index[i+1]]
}

// New returns a pointer to a new addr filled with the PatchOperation value passed in.
func (i PatchOperation) New() *PatchOperation {
	clone := i
	return &clone
}

var _PatchOperation_values = []PatchOperation{0, 1, 2}

var _PatchOperation_name_to_values = map[string]PatchOperation{
	_PatchOperation_name[0:7]:   0,
	_PatchOperation_name[7:13]:  1,
	_PatchOperation_name[13:16]: 2,
}

// ParsePatchOperationString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ParsePatchOperationString(s string) (PatchOperation, error) {
	if val, ok := _PatchOperation_name_to_values[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to PatchOperation values", s)
}

// PatchOperationValues returns all values of the enum
func PatchOperationValues() []PatchOperation {
	return _PatchOperation_values
}

// IsAPatchOperation returns "true" if the value is listed in the enum definition. "false" otherwise
func (i PatchOperation) Registered() bool {
	for _, v := range _PatchOperation_values {
		if i == v {
			return true
		}
	}
	return false
}

func _() {
	var _nil_PatchOperation_value = func() (val PatchOperation) { return }()

	// An "cannot convert PatchOperation literal (type PatchOperation) to type encoding.BinaryMarshaler" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ encoding.BinaryMarshaler = &_nil_PatchOperation_value

	// An "cannot convert PatchOperation literal (type PatchOperation) to type encoding.BinaryUnmarshaler" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ encoding.BinaryUnmarshaler = &_nil_PatchOperation_value
}

// MarshalBinary implements the encoding.BinaryMarshaler interface for PatchOperation
func (i PatchOperation) MarshalBinary() (data []byte, err error) {
	return []byte(i.String()), nil
}

// UnmarshalBinary implements the encoding.BinaryUnmarshaler interface for PatchOperation
func (i *PatchOperation) UnmarshalBinary(data []byte) error {
	var err error
	*i, err = ParsePatchOperationString(string(data))
	return err
}

func _() {
	var _nil_PatchOperation_value = func() (val PatchOperation) { return }()

	// An "cannot convert PatchOperation literal (type PatchOperation) to type json.Marshaler" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ json.Marshaler = _nil_PatchOperation_value

	// An "cannot convert PatchOperation literal (type PatchOperation) to type encoding.Unmarshaler" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ json.Unmarshaler = &_nil_PatchOperation_value
}

// MarshalJSON implements the json.Marshaler interface for PatchOperation
func (i PatchOperation) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for PatchOperation
func (i *PatchOperation) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("PatchOperation should be a string, got %s", data)
	}

	var err error
	*i, err = ParsePatchOperationString(s)
	return err
}

func _() {
	var _nil_PatchOperation_value = func() (val PatchOperation) { return }()

	// An "cannot convert PatchOperation literal (type PatchOperation) to type encoding.TextMarshaler" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ encoding.TextMarshaler = _nil_PatchOperation_value

	// An "cannot convert PatchOperation literal (type PatchOperation) to type encoding.TextUnmarshaler" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ encoding.TextUnmarshaler = &_nil_PatchOperation_value
}

// MarshalText implements the encoding.TextMarshaler interface for PatchOperation
func (i PatchOperation) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for PatchOperation
func (i *PatchOperation) UnmarshalText(text []byte) error {
	var err error
	*i, err = ParsePatchOperationString(string(text))
	return err
}

//func _() {
//	var _nil_PatchOperation_value = func() (val PatchOperation) { return }()
//
//	// An "cannot convert PatchOperation literal (type PatchOperation) to type yaml.Marshaler" compiler error signifies that the base type have changed.
//	// Re-run the go-enum command to generate them again.
//	var _ yaml.Marshaler = _nil_PatchOperation_value
//
//	// An "cannot convert PatchOperation literal (type PatchOperation) to type yaml.Unmarshaler" compiler error signifies that the base type have changed.
//	// Re-run the go-enum command to generate them again.
//	var _ yaml.Unmarshaler = &_nil_PatchOperation_value
//}

// MarshalYAML implements a YAML Marshaler for PatchOperation
func (i PatchOperation) MarshalYAML() (interface{}, error) {
	return i.String(), nil
}

// UnmarshalYAML implements a YAML Unmarshaler for PatchOperation
func (i *PatchOperation) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var s string
	if err := unmarshal(&s); err != nil {
		return err
	}

	var err error
	*i, err = ParsePatchOperationString(s)
	return err
}

func _() {
	var _nil_PatchOperation_value = func() (val PatchOperation) { return }()

	// An "cannot convert PatchOperation literal (type PatchOperation) to type driver.Valuer" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ driver.Valuer = _nil_PatchOperation_value

	// An "cannot convert PatchOperation literal (type PatchOperation) to type sql.Scanner" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ sql.Scanner = &_nil_PatchOperation_value
}

func (i PatchOperation) Value() (driver.Value, error) {
	return i.String(), nil
}

func (i *PatchOperation) Scan(value interface{}) error {
	if value == nil {
		return nil
	}

	str, ok := value.(string)
	if !ok {
		bytes, ok := value.([]byte)
		if !ok {
			return fmt.Errorf("value is not a byte slice")
		}

		str = string(bytes[:])
	}

	val, err := ParsePatchOperationString(str)
	if err != nil {
		return err
	}

	*i = val
	return nil
}

// PatchOperationSliceContains reports whether sunEnums is within enums.
func PatchOperationSliceContains(enums []PatchOperation, sunEnums ...PatchOperation) bool {
	var seenEnums = map[PatchOperation]bool{}
	for _, e := range sunEnums {
		seenEnums[e] = false
	}

	for _, v := range enums {
		if _, has := seenEnums[v]; has {
			seenEnums[v] = true
		}
	}

	for _, seen := range seenEnums {
		if !seen {
			return false
		}
	}

	return true
}

// PatchOperationSliceContainsAny reports whether any sunEnum is within enums.
func PatchOperationSliceContainsAny(enums []PatchOperation, sunEnums ...PatchOperation) bool {
	var seenEnums = map[PatchOperation]struct{}{}
	for _, e := range sunEnums {
		seenEnums[e] = struct{}{}
	}

	for _, v := range enums {
		if _, has := seenEnums[v]; has {
			return true
		}
	}

	return false
}
